apiVersion: v1
kind: Service
metadata:
  name: config-server
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: config-server
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: config-server
spec:
  selector:
    matchLabels:
      app: config-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - image: henrimarchal/config-server
          name: config-server
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          ports:
            - containerPort: 8888
              name: greeting
          readinessProbe:
            tcpSocket:
              host:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              host:
              port: 8080
            initialDelaySeconds: 45
            periodSeconds: 20
      imagePullSecrets:
        - name: regcred