apiVersion: v1
kind: Service
metadata:
  name: greeting
spec:
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: greeting
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: greeting
spec:
  selector:
    matchLabels:
      app: greeting
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: greeting
    spec:
      containers:
        - image: henrimarchal/greeting
          name: greeting
          ports:
            - containerPort: 9090
              name: greeting
      imagePullSecrets:
        - name: regcred