apiVersion: v1
kind: Service
metadata:
  name: name
spec:
  ports:
    - port: 7070
      targetPort: 7070
  selector:
    app: name
  externalTrafficPolicy: Local
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: name
spec:
  selector:
    matchLabels:
      app: name
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: name
    spec:
      containers:
        - image: henrimarchal/name
          name: name
          resources:
            limits:
              cpu: 1000m
            requests:
              cpu: 500m
          ports:
            - containerPort: 7070
              name: name
          readinessProbe:
            tcpSocket:
              host:
              port: 7070
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              host:
              port: 7070
            initialDelaySeconds: 45
            periodSeconds: 20
      imagePullSecrets:
        - name: regcred