server.port: 7070
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:mysql://${MYSQL_HOST:localhost}:3306/scd_name"
    username: scd
    password: scd
    driver-class-name: com.mysql.cj.jdbc.Driver
#spring.jpa.show-sql: true